defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  - override hydra/launcher: a100.yaml
  - _self_

hydra:
  mode: MULTIRUN
  # sweeper:
  #   params:
  #     attack_name: pgd, gcg, autodan
  #     datasets.adv_behaviors.idx: range(0, 20)
  run:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

dtype: float16
name: testing
log_file: ../../../../outputs/

# overrides for parallelism
attack_name: null
dataset_name: null
model_name: null