defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  # - paths
  # - override hydra/launcher: mila_generic
  - _self_

hydra:
  # mode: MULTIRUN
  sweeper:
    params:
      datasets.rf_test.idx: "range(0,160,step=6)"
  run:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: RF_mistralv3
root_dir: ${oc.env:PWD}
save_dir: ${root_dir}/outputs/rf_test
log_file_path: ${save_dir}/redflag_mistralv3/${attack_name}/run-${datasets.rf_test.idx}__${now:%H-%M-%S}.json 

log_toks_strs: True
hf_offline_mode: True
attacks.gcg.num_steps: 300
datasets.rf_test.batch: 6

# overrides for parallelism
attack_name: gcg
dataset_name: rf_test
model_name: redflag-tokens/mistralv3-rf

wandb: null
# wandb: 
#   name: null
#   project: redflag_evals
#   entity: busycalibrating
