defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  # - paths
  # - override hydra/launcher: mila_generic
  - _self_

hydra:
#   mode: MULTIRUN
  sweeper:
    params:
      datasets.rf_test.idx: "range(0,160,step=20)"
  run:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: RF_phi3-5_base
root_dir: ${oc.env:PWD}
save_dir: ${root_dir}/outputs/rf_test
log_file_path: ${save_dir}/redflag_phi3-5_base/${attack_name}/run-${datasets.rf_test.idx}__${now:%H-%M-%S}.json 

log_toks_strs: True
hf_offline_mode: True
attacks:
  gcg:
    num_steps: 300
datasets:
  rf_test:
    batch: 20
    path: ${oc.env:HOME}/harmful-harmless-eval/

slurm_copy_hf_cache:
  models:
    - microsoft/Phi-3.5-mini-instruct
    - lmsys/vicuna-13b-v1.5
    - cais/HarmBench-Llama-2-13b-cls

# overrides for parallelism
attack_name: pair  # gcg
dataset_name: rf_test
model_name: microsoft/Phi-3.5-mini-instruct

wandb: null
# wandb: 
#   name: null
#   project: redflag_evals
#   entity: busycalibrating
