defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  - paths
  - override hydra/launcher: a100h100.yaml
  - _self_

hydra:
  run:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: testing
save_dir: ${root_dir}/outputs/
embed_dir: ${root_dir}/embeddings/
overwrite: false

classifiers: ["strong_reject"] # anything from judgezoo

# overrides for parallelism
attack: null
dataset: adv_behaviors
model: null