defaults:
  - attacks: attacks
  - datasets: datasets_dd
  - models: models
  # - override hydra/launcher: l40s_mila.yaml
  - _self_

hydra:
  # mode: MULTIRUN
  # sweeper:
  #   params:
  #     attack_name: pgd, gcg, autodan
  #     datasets.adv_behaviors.idx: range(0, 20)
  run:
    dir: ${oc.env:SCRATCH}/2024/llm-quick-check/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${oc.env:SCRATCH}/2024/llm-quick-check/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

dtype: float16
name: testing
log_file: ${oc.env:SCRATCH}/2024/llm-quick-check/outputs/

# overrides for parallelism
attack_name: null
dataset_name: null
model_name: null