defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  # - paths
  # - override hydra/launcher: mila_generic
  - _self_

hydra:
  # mode: MULTIRUN
  # sweeper:
  #   params:
  #     datasets.adv_behaviors.idx: 0,2
  run:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: RF_mistralv3
root_dir: ${oc.env:PWD}
save_dir: ${root_dir}/outputs/
log_file_path: ${save_dir}/redflag_mistralv3/${attack_name}/run-${datasets.adv_behaviors.idx}__${now:%H-%M-%S}.json 

log_toks_strs: True
hf_offline_mode: True

# overrides for parallelism
attack_name: gcg
dataset_name: adv_behaviors
model_name: redflag-tokens/mistralv3-rf

wandb: null
# wandb: 
#   name: null
#   project: redflag_evals
#   entity: busycalibrating