defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  - paths
  - override hydra/launcher: a100h100.yaml
  - _self_

hydra:
  run:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: testing
save_dir: ${root_dir}/outputs/
overwrite: false

classifiers: ["strong_reject"] # Options: "strong_reject", "cais", "llama_guard_3_8b", "overrefusal", etc. (can be list[str]|null)

# overrides for parallelism
attack: null
dataset: adv_behaviors
model: null