defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  #- override hydra/launcher: a100h100.yaml
  - _self_

hydra:
  mode: MULTIRUN
  run:
    dir: /ceph/ssd/staff/schwinn/experiments/2025/capo_vlm/attacks/attack_run/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: /ceph/ssd/staff/schwinn/experiments/2025/capo_vlm/attacks/attack_run/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: testing
log_file: /ceph/ssd/staff/schwinn/experiments/2025/capo_vlm/attacks/attack_json/

# overrides for parallelism
attack_name: null
dataset_name: null
model_name: null